config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    # resources :sessions

    root "homes#index"
    scope :admin do
      root "dashboards#index"
      resources :categories
      resources :products
      resources :users
      resources :customers
      resources :orders
      get "invoice/:id" => "orders#invoice", :as => :invoice
    end
    scope :shopping do
      resources :homes
      get "customer_info/:id" => "customers#customer_info", :as => :customer_info
      get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
      patch "customer_info/:id" => "customers#update_customer_info"
      put "customer_info/:id" => "customers#update_customer_info"
      get "product_detail/:id" => "products#product_detail", :as => :product_detail
      resources :customers
    end



    mount ActionCable.server => '/cable'

    get "cart" => "cart#show"
    get "cart/add/:id" => "cart#add", :as => :add_to_cart
    post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
    post "cart/checkout" => "cart#checkout", :as => :checkout

    post 'session' => 'sessions#create', :as=> :session_customer
    get 'signup' => 'customers#new',:as=> :signup
    get 'logout' => 'sessions#destroy', :as => :logout
    get 'login' => 'sessions#new', :as => :login
    get "dashboard" => 'dashboards#index', :as => :dashboard_page

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :login_required
  before_action :find_cart

  def add
    @cart.save if @cart.new_record?
    session[:cart_id] = @cart.id
    product = Product.find(params[:id])
    LineItem.create! :order => @cart, :product => product, :price => product.product_price
    @cart.recalculate_price!

    flash[:notice] = "Item added to cart!"
    redirect_to '/cart'
  end

  def remove
    item = @cart.line_items.find(params[:id])
    item.destroy
    @cart.recalculate_price!
    flash[:notice] = "Item removed from cart"
    redirect_to '/cart'
  end

  def checkout
    @cart.checkout!
    session.delete(:cart_id)
    flash[:notice] = "Thank you for your purchase! We will ship it shortly!"
    redirect_to "/"
  end



  private
    def find_cart
      @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_customer.orders.build
      @category = Category.all
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/show.html.erb
<%=render "shared/end-user-nav-bar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/end-user-left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel" style="background: #f3f3f4;">
          <div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-md-9">

                    <div class="ibox">
                        <div class="ibox-title">
                            <span class="pull-right">(<strong><%=@cart.line_items.count%></strong>) items</span>
                            <h5>Items in your cart</h5>
                        </div>
                        <% unless @cart.line_items.any? %>
                            <p>You don't have any items in your cart. <%= link_to "Go Add Some", root_path %>
                        <% end %>

                    <% for line_item in @cart.line_items %>
                        <div class="ibox-content">
                            <div class="table-responsive">
                                <table class="table shoping-cart-table">

                                    <tbody>
                                    <tr>
                                        <td width="90">
                                            <div class="cart-product-imitation">
                                              <%if line_item.product.image.blank?%>
                                                  [Image Not Found]
                                                <%else%>
                                                  <%=image_tag(line_item.product.image,:class=>"image-cart")%>
                                              <%end%>
                                            </div>
                                        </td>
                                        <td class="desc">
                                            <h3>
                                            <a href="#" class="text-navy">
                                              <%= line_item.product.product_name %>
                                            </a>
                                            </h3>
                                            <p class="small">
                                              <%if line_item.product.category.description%>
                                                  <p>No description</p>
                                                <%else%>
                                                <%=line_item.product.category.description%>
                                              <%end%>
                                            </p>
                                            <dl class="small m-b-none">
                                                <dt>Description lists</dt>
                                                <%if line_item.product.category.description%>
                                                    <dd>No description</dd>
                                                  <%else%>
                                                  <dd><%=line_item.product.category.description%></dd>
                                                <%end%>
                                            </dl>

                                            <div class="m-t-sm">
                                                <%=link_to add_to_cart_path(line_item.product.id),:class=>"text-muted" do%>
                                                  <i class="fa fa-plus"></i> Add More
                                                <%end%>
                                                |
                                                <%=link_to remove_from_cart_path(line_item), :method => :post, :class=>"text-muted" do%>
                                                  <i class="fa fa-trash"></i> Remove Item
                                                <%end%>
                                            </div>
                                        </td>

                                        <td>
                                            <h4><%= number_to_currency line_item.price %></h4>
                                            <s class="small text-muted">$230,00</s>
                                        </td>

                                    </tr>
                                    </tbody>
                                </table>
                            </div>

                        </div>
                      <%end%>
                        <div class="ibox-content">
                          <%= form_tag checkout_path do |f| %>
                            <%= submit_tag "Checkout Now!",:class=>"btn btn-primary pull-right" do%>
                              <i class="fa fa-shopping"></i> Checkout
                            <%end%>
                            <%= link_to root_path,:class=>"btn btn-white" do%>
                              <i class="fa fa-arrow-left"></i> Continue Shopping
                            <%end%>
                          <% end %>
                        </div>
                    </div>

                </div>
                <div class="col-md-3">

                    <div class="ibox">
                        <div class="ibox-title">
                            <h5>Cart Summary</h5>
                        </div>
                        <div class="ibox-content">
                            <span>
                                Total
                            </span>
                            <h2 class="font-bold">
                                <%= number_to_currency @cart.total_price %>
                            </h2>

                            <hr/>
                            <span class="text-muted small">
                                *For United States, France and Germany applicable sales tax will be applied
                            </span>
                            <div class="m-t-sm">
                                <div class="btn-group">
                                <%= form_tag checkout_path do |f| %>
                                  <%= submit_tag "Checkout Now!",:class=>"btn btn-primary btn-sm" do%>
                                    <i class="fa fa-shopping"></i> Checkout
                                  <%end%>
                                  <%= link_to "Cancle", root_path,:class=>"btn btn-white btn-sm"%>

                                  <%end%>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="ibox">
                        <div class="ibox-title">
                            <h5>Support</h5>
                        </div>
                        <div class="ibox-content text-center">



                            <h3><i class="fa fa-phone"></i> +85595477325</h3>
                            <span class="small">
                                Please contact with us if you have any questions. We are avalible 24h.
                            </span>


                        </div>
                    </div>

                    <div class="ibox">
                        <div class="ibox-content">

                            <p class="font-bold">
                            Other products you may be interested
                            </p>

                            <hr/>
                            <div>
                                <a href="#" class="product-name"> Product 1</a>
                                <div class="small m-t-xs">
                                    Many desktop publishing packages and web page editors now.
                                </div>
                                <div class="m-t text-righ">

                                    <a href="#" class="btn btn-xs btn-outline btn-primary">Info <i class="fa fa-long-arrow-right"></i> </a>
                                </div>
                            </div>
                            <hr/>
                            <div>
                                <a href="#" class="product-name"> Product 2</a>
                                <div class="small m-t-xs">
                                    Many desktop publishing packages and web page editors now.
                                </div>
                                <div class="m-t text-righ">

                                    <a href="#" class="btn btn-xs btn-outline btn-primary">Info <i class="fa fa-long-arrow-right"></i> </a>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>

        </div><!-- contentpanel -->
      <%=render "shared/end-user-footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>