config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    # resources :sessions

    root "homes#index"
    scope :admin do
      root "dashboards#index"
      resources :categories
      resources :products
      resources :users
      resources :customers
      resources :orders
      get "invoice/:id" => "orders#invoice", :as => :invoice
    end
    scope :shopping do
      resources :homes
      get "customer_info/:id" => "customers#customer_info", :as => :customer_info
      get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
      patch "customer_info/:id" => "customers#update_customer_info"
      put "customer_info/:id" => "customers#update_customer_info"
      get "product_detail/:id" => "products#product_detail", :as => :product_detail
      resources :customers
    end



    mount ActionCable.server => '/cable'

    get "cart" => "cart#show"
    get "cart/add/:id" => "cart#add", :as => :add_to_cart
    post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
    post "cart/checkout" => "cart#checkout", :as => :checkout

    post 'session' => 'sessions#create', :as=> :session_customer
    get 'signup' => 'customers#new',:as=> :signup
    get 'logout' => 'sessions#destroy', :as => :logout
    get 'login' => 'sessions#new', :as => :login
    get "dashboard" => 'dashboards#index', :as => :dashboard_page

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  belongs_to :user
  validates :category_name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  #Association
  has_many :orders, :dependent => :destroy
  validates :password, presence: true
  attr_accessor :password
  before_save :prepare_password

  #Validation
  has_attached_file :image, styles: {
    medium: "300x300>",
    thumb: "100x100>"
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /(?=.*[A-Za-z._@])/, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  #Class Method
  def self.authenticate(login, pass)
    customer = find_by_username(login) || find_by_email(login)
    return customer if customer && customer.matching_password?(pass)
  end

  #Instance Method
  def matching_password?(pass)
    self.password_hashL == encrypt_password(pass)
  end

  private

    def prepare_password
      unless password.blank?
        self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
        self.password_hashL = encrypt_password(password)
      end
    end

    def encrypt_password(pass)
      Digest::SHA1.hexdigest([pass, password_salt].join)
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  #Association
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  #Association
  has_many :line_items, :dependent => :destroy
  belongs_to :customer
  #Scope
  scope :in_progress, ->{where("orders.checked_out_at IS NULL")}
  scope :complete, -> {where("orders.checked_out_at IS NOT NULL")}

  COMPLETE = "complete"
  IN_COMPLETE = "in_complete"

  #Class Method
  def self.find_with_product(product)
    return [] unless product
    complete.joins(:line_items).where(["line_items.product_id = ?", product.id]).order("orders.checked_out_at DESC")
  end

  #Instance Method
  def checkout!
    self.checked_out_at = Time.now
    self.save
  end

  def recalculate_price!
    self.total_price = line_items.inject(0.0){|sum, line_item| sum += line_item.price }
    save!
  end

  def state
    checked_out_at.nil? ? IN_COMPLETE : COMPLETE
  end

  # def self.count_complete_item
  #   where("checked_out_at <> ?", !nil).count
  # end
  # def display_name
  #   ActionController::Base.helpers.number_to_currency(total_price) +
  #       " - Order ##{id} (#{user.username})"
  # end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :line_items

#Validation
  validates :product_name, presence: true
  validates :product_unit, presence: true
  validates :product_price, presence: true

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Association
  has_many :categories
  has_many :products
  
  #Devise
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  #Validation
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #instance method
  def set_default_role
    self.role ||= :user
  end

  def full_name
    "#{first_name}" "#{last_name}"
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :login_required
  before_action :find_cart

  def add
    @cart.save if @cart.new_record?
    session[:cart_id] = @cart.id
    product = Product.find(params[:id])
    LineItem.create! :order => @cart, :product => product, :price => product.product_price
    @cart.recalculate_price!

    flash[:notice] = "Item added to cart!"
    redirect_to '/cart'
  end

  def remove
    item = @cart.line_items.find(params[:id])
    item.destroy
    @cart.recalculate_price!
    flash[:notice] = "Item removed from cart"
    redirect_to '/cart'
  end

  def checkout
    @cart.checkout!
    session.delete(:cart_id)
    flash[:notice] = "Thank you for your purchase! We will ship it shortly!"
    redirect_to "/"
  end



  private
    def find_cart
      @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_customer.orders.build
      @category = Category.all
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :current_customer

  def index
    @products = Product.all
    @category = Category.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  def current_customer
    @current_customer ||= Customer.find(session[:customer_id]) if session[:customer_id]
  end

  def logged_in?
    current_customer
  end

  def login_required
    unless logged_in?
      flash[:error] = "You must first log in or sign up before accessing this page."
      store_target_location
      redirect_to login_url
    end
  end

  def redirect_to_target_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end

  private

    def store_target_location
      session[:return_to] = request.url
    end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper


end

app/helpers/orders_helper.rb
module OrdersHelper
  def total_price_zero(order)
    order = 0
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_category(product)
      if product.category.category_name == "Please Select Category"
        "Uncategory"
      else
        product.category.category_name
      end
    end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%=render "shared/google-font/font"%>
    <title>Administrator</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all'%>
  </head>

  <body class="signin">
    <%= yield %>
    <%=javascript_include_tag 'application'%>
  </body>
</html>

app/views/shared/_end-user-footer.html.erb
<footer><!-- footer -->
  <p class="col-xs-12 footer-copyright">
    Powered by <b>Chhouk Tit Panhara</b>
  </p>
</footer>

app/views/shared/_end-user-left-panel.html.erb
<div class="leftpanel">
  <br><br><br>
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="/"><i class="fa fa-home"></i> <span>Home</span></a></li>

    <li class="parent"><a href="#"><i class="fa fa-edit"></i> <span>About Me</span></a></li>

    <li class="parent"><a href="#"><i class="fa fa-edit"></i> <span>Contact Me</span></a></li>



  </ul>
</div><!-- leftpanel -->

app/views/shared/_end-user-nav-bar.html.erb
<header>
  <div class="headerwrapper">
    <div class="header-left">
      <a href="/" class="logo">
        <h4 class="admin-logo"><img class="logo-img" src="/logo.png" alt=""> Panha Online </h4>

      </a>

      <div class="pull-right">
        <a href="#" class="menu-collapse">
          <i class="fa fa-bars"></i>
        </a>
      </div>
    </div><!-- header-left -->

    <div class="header-right">
      <div class="pull-right">
        <!-- <form class="form form-search" action="http://www.ravijaiswal.com/Moldavite/search-results.html">
          <input type="search" class="form-control" placeholder="Search" />
        </form> -->
        <div class="btn-group btn-group-option">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          </ul>
            <%if logged_in?%>
              <%if current_customer.image.blank?%>
                  <img class="img-circle avatar-img" alt="" src="/profile.png">
                  <span class="username">Welcome <%=current_customer.username%>!</span>
                <%else%>
                  <img class="img-circle avatar-img" alt="" src="<%=current_customer.image%>">
                  <span class="username">Welcome <%=current_customer.username%>!</span>
              <%end%>
              <%else%>
            <%end%>
        		<i class="fa fa-caret-down"></i>
          </button>
          <ul class="dropdown-menu pull-right" role="menu">
            <% if logged_in? %>
                <li>
                  <%= link_to edit_customer_info_path(current_customer) do %>
                    <i class="glyphicon glyphicon-pencil"></i>
                    Edit Profile
                  <%end%>
                </li>

                <li>
                  <%= link_to customer_info_path(current_customer) do %>
                    <i class="glyphicon glyphicon-pencil"></i>
                    Info
                  <%end%>
                </li>

                <li>
                  <%= link_to logout_path do %>
                  <i class="glyphicon glyphicon-log-out"></i>
                  Sign Out
                  <%end%>
                </li>
            <% else %>
              <li><%= link_to "Sign up", signup_path %></li>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </div><!-- btn-group -->
      </div><!-- pull-right -->
    </div><!-- header-right -->
  </div><!-- headerwrapper -->
</header>

app/views/shared/_footer.html.erb
<footer><!-- footer -->
  <p class="col-xs-12 footer-copyright">
    Powered by <b>Chhouk Tit Panhara</b>
  </p>
</footer>

app/views/shared/_left-panel.html.erb
<div class="leftpanel">
  <div class="media profile-left">
    <%if user_signed_in?%>
      <%=link_to users_path,:class=>"pull-left profile-thumb" do%>
      <%if current_user.image.blank?%>
        <img class="img-circle" src="/profile.png" alt="">
      <%else%>
        <img class="img-circle" src="<%=current_user.image%>" alt="">
      <%end%>
    <%end%>

    <div class="media-body">

      <h4 class="media-heading"><%=current_user.username%></h4>
        <span class="user-options">
          <%=link_to users_path do%>
            <i class="glyphicon glyphicon-user"></i>
          <%end%>
          <%=link_to edit_user_registration_path do%>
            <i class="glyphicon glyphicon-cog"></i>
          <%end%>
          <%=link_to destroy_user_session_path do%>
            <i class="glyphicon glyphicon-log-out"></i>
          <%end%>

        </span>
    </div>
    <%end%>

  </div><!-- media -->


  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="/admin"><i class="fa fa-home"></i> <span>Dashboard</span></a></li>
    <li class="parent">
      <a href="#">
        <i class="fa fa-suitcase"></i>
        <span>Product</span>
      </a>

      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add Product", new_product_path%>
          </li>
          <li>
            <%=link_to "Product List", products_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Product List", products_path%>
          </li>
        <%end%>

      </ul>
    </li>

    <li class="parent"><a href="#"><i class="fa fa-edit"></i> <span>Category</span></a>
      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add Category", new_category_path%>
          </li>
          <li>
            <%=link_to "Category List", categories_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Product List", categories_path%>
          </li>
        <%end%>

      </ul>
    </li>

    <li class="parent"><a href="#"><i class="fa fa-file-text"></i> <span>Order</span></a>
      <ul class="children">
        <li><%=link_to "Order List", orders_path%></li>

      </ul>
    </li>

    <li class="parent"><a href="#"><i class="fa fa-file-text"></i> <span>Customer</span></a>
      <ul class="children">
        <li><%=link_to "Customer List", customers_path%></li>

      </ul>
    </li>


    <li class="parent"><a href="#"><i class="fa fa-file-text"></i> <span>Report</span></a>
      <ul class="children">
        <li><%=link_to "Report", "#"%></li>

      </ul>
    </li>
  </ul>
</div><!-- leftpanel -->

app/views/shared/_navbar.html.erb
<header>
  <div class="headerwrapper">
    <div class="header-left">
      <a href="/admin" class="logo">
        <h4 class="admin-logo"><img src="/logo.png" alt=""> Administrator </h4>

      </a>

      <div class="pull-right">
        <a href="#" class="menu-collapse">
          <i class="fa fa-bars"></i>
        </a>
      </div>
    </div><!-- header-left -->

    <div class="header-right">
      <div class="pull-right">
        <!-- <form class="form form-search" action="http://www.ravijaiswal.com/Moldavite/search-results.html">
          <input type="search" class="form-control" placeholder="Search" />
        </form> -->

        <div class="btn-group btn-group-option">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <%if user_signed_in?%>
              <%if current_user.image.blank?%>
                  <img class="img-circle avatar-img" alt="" src="/profile.png">
                <%else%>
                  <img class="img-circle avatar-img" alt="" src="<%=current_user.image%>">
              <%end%>
              <%else%>
            <%end%>
        		<span class="user-name"><%=current_user.username%></span>
        		<i class="fa fa-caret-down"></i>
          </button>
          <ul class="dropdown-menu pull-right" role="menu">
            <% if user_signed_in? %>
              <% if current_user.try(:admin?) %>
                <li>
                  <%= link_to current_user do %>
                    <i class="glyphicon glyphicon-user"></i>
                    My Profile
                  <%end%>
                  </li>
              <% end %>
            <% end %>

              <% if user_signed_in? %>
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <i class="glyphicon glyphicon-cog"></i>
                    Accont Setting
                  <%end%>
                </li>

                <li>
                  <%= link_to destroy_user_session_path, :method => 'delete' do %>
                    <i class="glyphicon glyphicon-log-out"></i>
                    Sign Out
                  <%end%>
                </li>
              <% else %>

              <% end %>
          </ul>
        </div><!-- btn-group -->
      </div><!-- pull-right -->
    </div><!-- header-right -->
  </div><!-- headerwrapper -->
</header>

app/views/shared/google-font/_font.html.erb
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> 

app/views/signup/_signup.html.erb
<%=render "shared/end-user-nav-bar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/end-user-left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel" style="background: #f3f3f4;">
          <div class="middle-box text-center loginscreen animated fadeInDown">
            <div>

              <% if flash[:notice] -%>
                <div class="alert alert-danger alert-dismissable">
                  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                  <a class="alert-link" href="#"><%= flash[:notice] %></a>.
                </div>
              <% end %>
                <%= form_for @customer,:class=>"m-t" do |f| %>
                  <%if f.error_messages %>
                    <div class="alert alert-danger alert-dismissable">
                      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                      <a class="alert-link" href="#"><%= f.error_messages %></a>.
                    </div>
                  <%else%>

                  <%end%>
                  <h3>Register To Panhara Online Shop</h3>
                  <p>Create account to see it in action.</p>
                  <div class="form-group">
                      <%= f.label :username %>
                      <%= f.text_field :username,:class=>"form-control" %>
                  </div><!-- /.field-row -->

                  <div class="form-group">
                      <%= f.label :email %>
                      <%= f.text_field :email,:class=>"form-control" %>
                  </div><!-- /.field-row -->

                  <div class="form-group">
                      <%= f.label :password %>
                      <%= f.password_field :password,:class=>"form-control"%>
                  </div><!-- /.field-row -->

                  <div class="form-group">
                    <%= f.label :password_confirmation, "Confirm Password" %>
                    <%= f.password_field :password_confirmation,:class=>"form-control" %>
                  </div><!-- /.field-row -->

                  <div class="form-group">
                    <div class="checkbox i-checks"><label> <input type="checkbox"><i></i> Agree the terms and policy </label></div>
                  </div>

                  <%=f.submit "Register", :class=>"btn btn-primary block full-width m-b"%>
                  <p class="text-muted text-center"><small>Already have an account?</small></p>
                  <%=link_to "Login", login_path, :class=>"btn btn-sm btn-white btn-block"%>
            <% end %>
          </div>

        </div>
      </div><!-- contentpanel -->

      <%=render "shared/end-user-footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>