config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    # resources :sessions

    root "homes#index"
    scope :admin do
      root "dashboards#index"
      resources :categories
      resources :products
      resources :users
      resources :customers
      resources :orders
      get "invoice/:id" => "orders#invoice", :as => :invoice
    end
    scope :shopping do
      resources :homes
      get "customer_info/:id" => "customers#customer_info", :as => :customer_info
      get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
      patch "customer_info/:id" => "customers#update_customer_info"
      put "customer_info/:id" => "customers#update_customer_info"
      get "product_detail/:id" => "products#product_detail", :as => :product_detail
      resources :customers
    end



    mount ActionCable.server => '/cable'

    get "cart" => "cart#show"
    get "cart/add/:id" => "cart#add", :as => :add_to_cart
    post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
    post "cart/checkout" => "cart#checkout", :as => :checkout

    post 'session' => 'sessions#create', :as=> :session_customer
    get 'signup' => 'customers#new',:as=> :signup
    get 'logout' => 'sessions#destroy', :as => :logout
    get 'login' => 'sessions#new', :as => :login
    get "dashboard" => 'dashboards#index', :as => :dashboard_page

end

app/models/customer.rb
class Customer < ApplicationRecord
  #Association
  has_many :orders, :dependent => :destroy
  validates :password, presence: true
  attr_accessor :password
  before_save :prepare_password

  #Validation
  has_attached_file :image, styles: {
    medium: "300x300>",
    thumb: "100x100>"
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /(?=.*[A-Za-z._@])/, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  #Class Method
  def self.authenticate(login, pass)
    customer = find_by_username(login) || find_by_email(login)
    return customer if customer && customer.matching_password?(pass)
  end

  #Instance Method
  def matching_password?(pass)
    self.password_hashL == encrypt_password(pass)
  end

  private

    def prepare_password
      unless password.blank?
        self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
        self.password_hashL = encrypt_password(password)
      end
    end

    def encrypt_password(pass)
      Digest::SHA1.hexdigest([pass, password_salt].join)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:destroy]
  before_action :admin_only, only:[:destroy]
  before_action :login_required, only:[:edit,:customer_info,:edit_customer_info,:update_customer_info]
  before_action :current_customer, only:[:customer_info,:edit_customer_info,:update_customer_info]

  def customer_info
    @cust = Customer.find(params[:id])
    if @cust != current_customer
      render file: "#{Rails.root}/public/500.html", layout: false, status: 500
    else

    end
    @orders = @cust.orders

    @order = Order.find(params[:id])
    @lineitems = @order.line_items
    @fields = ["ID","Customer Name","Email","Image"]
  end

  def edit_customer_info
    @cust = Customer.find(params[:id])
  end

  def update_customer_info
    @cust = Customer.find(params[:id])
    if @cust != current_customer
      if @cust.update(customer_params)
        redirect_to :action => 'customer_info'
      else
        flash[:notice] = "All Fill Require"
        render 'edit_customer_info'
      end
    else
      flash[:notice] = "Your Attempt To Hack This Men Account"
      render 'edit_customer_info'
    end
  end

  def index
    @customers = Customer.all
    @fields = ["ID","Customer Name","Email","Image"]
  end

  def show
    @customer = Customer.find(params[:id])
    @orders = @customer.orders
    @fields = ["Order ID","State","Date","Total"]
  end

  def new
    @category = Category.all
    @customer = Customer.new
  end

  def create
    @category = Category.all
    @customer = Customer.new(customer_params)
    if @customer.save
      session[:customer_id] = @customer.id
      flash[:notice] = "Thank For Sign Up"
      redirect_to :homes
    else
      render :action => 'new'
    end
  end


  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if session[:customer_id] == @customer.id
      if @customer.update(customer_params)
        redirect_to logout_path
      else
        flash[:notice] = "All Fill Require"
        render :edit
      end
    else
      flash[:notice] = "Your Attempt To Hack This Men Account"
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to customers_url, notic: "Customer Has Been Deleted"
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def admin_only
      unless current_user.admin?
        redirect_to root_path, :alert => "Access denied."
      end
    end

    def customer_params
      params.require(:customer).permit(:username,:email,:password,:salt,:encrypted_password)
    end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  def current_customer
    @current_customer ||= Customer.find(session[:customer_id]) if session[:customer_id]
  end

  def logged_in?
    current_customer
  end

  def login_required
    unless logged_in?
      flash[:error] = "You must first log in or sign up before accessing this page."
      store_target_location
      redirect_to login_url
    end
  end

  def redirect_to_target_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end

  private

    def store_target_location
      session[:return_to] = request.url
    end
end

app/views/customers/customer_info.html.erb
<%=render "shared/end-user-nav-bar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/end-user-left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel">
          <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-md-8">
                  <div class="ibox float-e-margins">
                    <div class="ibox-title">
                      <h5>Order History</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>

                        <div class="ibox-content">
                            <table class="table table-hover no-margins">
                                <thead>
                                <tr>
                                  <%@fields.each do |f|%>
                                    <th><%=f%></th>
                                  <%end%>
                                </tr>
                                </thead>
                                <tbody>

                                <%@lineitems.each do |item|%>
                                  <tr>
                                    <td><%=item.product.product_name%></td>
                                    <%if item.order.state == "complete"%>
                                      <td><span class="label label-primary"><%=item.order.state%></span></td>
                                    <%else%>
                                    <%end%>
                                    <td><%=item.order.checked_out_at%></td>
                                    <%if item.order.state == "complete"%>
                                      <td><%=number_to_currency(item.price)%></td>
                                    <%else%>
                                      <td><%=number_to_currency(0.0)%></td>
                                  </tr>
                                  <%end%>
                                <%end%>
                                </tbody>
                                <tr>
                                  <%if @order.state == "complete"%>
                                    <td> <strong>Total: </strong> <%=number_to_currency(@order.total_price)%></td>
                                  <%else%>
                                    <td><%=number_to_currency(total_price_zero(0))%></td>
                                  <%end%>
                                </tr>
                            </table>
                        </div>

                    </div>
                </div>

                <div class="col-md-4">
                  <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Who Buy Your Product?</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>

                    <div class="ibox-content">
                        <ul class="todo-list m-t small-list">
                          <h5>Username</h5>
                          <li><%=@cust.username%></li>
                          <h5>E-mail</h5>
                          <li><%=@cust.email%></li>
                          <h5>Created At</h5>
                          <li><%=@cust.created_at%></li>
                          <%= link_to edit_product_path, :class => 'btn btn-primary btn-sm',:rel=>"tooltip",:title=>"Edit",:style=>"margin-right:10px;" do %>
                            <i class="fa fa-pencil" style="font-size: 15px;"></i> Edit Product
                          <% end %>

                          <%= link_to @product,method: :delete,data: {confirm: "Are You Sure?"}, :class => 'btn btn-danger btn-sm',:rel=>"tooltip",:title=>"Delete" do %>
                            <i class="fa fa-trash-o" style="font-size: 15px;"></i> Delete
                          <% end %>
                        </ul>
                    </div>
                    </div>
                </div>
            </div>
        </div>
      </div><!-- contentpanel -->
    <%=render "shared/footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>

app/views/customers/edit.html.erb
<%=render "signup/signup"%>

app/views/customers/edit_customer_info.html.erb
<%=render "shared/end-user-nav-bar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/end-user-left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel" style="background: #f3f3f4;">
          <div class="middle-box text-center loginscreen animated fadeInDown">
            <div>

              <% if flash[:notice] -%>
                <div class="alert alert-danger alert-dismissable">
                  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                  <a class="alert-link" href="#"><%= flash[:notice] %></a>.
                </div>
              <% end %>
                <%= form_for @cust,:class=>"m-t" do |f| %>
                  <%if f.error_messages %>
                    <div class="alert alert-danger alert-dismissable">
                      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                      <a class="alert-link" href="#"><%= f.error_messages %></a>.
                    </div>
                  <%else%>

                  <%end%>
                  <h3>Register To Panhara Online Shop</h3>
                  <p>Create account to see it in action.</p>
                  <div class="form-group">
                      <%= f.label :username %>
                      <%= f.text_field :username,:class=>"form-control" %>
                  </div><!-- /.field-row -->

                  <div class="form-group">
                      <%= f.label :email %>
                      <%= f.text_field :email,:class=>"form-control" %>
                  </div><!-- /.field-row -->

                  <div class="form-group">
                      <%= f.label :password %>
                      <%= f.password_field :password,:class=>"form-control"%>
                  </div><!-- /.field-row -->

                  <div class="form-group">
                    <%= f.label :password_confirmation, "Confirm Password" %>
                    <%= f.password_field :password_confirmation,:class=>"form-control" %>
                  </div><!-- /.field-row -->

                  <div class="form-group">
                    <div class="checkbox i-checks"><label> <input type="checkbox"><i></i> Agree the terms and policy </label></div>
                  </div>

                  <%=f.submit "Register", :class=>"btn btn-primary block full-width m-b"%>
                  <p class="text-muted text-center"><small>Already have an account?</small></p>
                  <%=link_to "Login", login_path, :class=>"btn btn-sm btn-white btn-block"%>
            <% end %>
          </div>

        </div>
      </div><!-- contentpanel -->

      <%=render "shared/end-user-footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>

app/views/customers/index.html.erb
<%=render "shared/navbar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel">
          <section class="panel panel-default">
            <div class="panel-body weather-row">
              <div class="row" style="background:#fff;padding:10px;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;margin-bottom:15px;">
                <div class="col-md-12">
                  <h5 class="lg-title mb5">Product</h5>
                  <p class="mb20">An example of table with actions in every rows.</p>
                  <div class="table-responsive">
                    <table class="table mb30">
                      <thead>
                        <tr>
                          <%@fields.each do |f|%>
                            <th><%=f%></th>
                          <%end%>
                        </tr>
                      </thead>
                      <%@customers.each do |customer|%>
                      <tbody>
                        <tr>
                          <td><%=customer.id%></td>
                          <td><%=customer.username %></td>
                          <td><%=customer.email%></td>
                          <td><%=image_tag(customer.image,:style=>"width:30%;")%></td>
                          <td class="td-actions text-right">

                          <% if current_user.try(:admin?) %>
                              <%= link_to customer, :class => 'btn btn-success btn-simple btn-xs',:rel=>"tooltip",:title=>"View" do %>
                                  <i class="fa fa-eye" style="font-size: 15px;"></i>
                              <% end %>

                              <%= link_to edit_customer_path(customer.id), :class => 'btn btn-success btn-simple btn-xs',:rel=>"tooltip",:title=>"Edit" do %>
                                  <i class="fa fa-pencil" style="font-size: 15px;"></i>
                              <% end %>

                              <%= link_to customer,method: :delete,data: {confirm: "Are You Sure?"}, :class => 'btn btn-danger btn-simple btn-xs',:rel=>"tooltip",:title=>"Delete" do %>
                                  <i class="fa fa-trash-o" style="font-size: 15px;"></i>
                              <% end %>
                            <%else%>
                              <%= link_to customer, :class => 'btn btn-success btn-simple btn-xs',:rel=>"tooltip",:title=>"View" do %>
                                  <i class="fa fa-eye" style="font-size: 15px;"></i>
                              <% end %>
                          <%end%>
                          </td>
                        </tr>
                      </tbody>
                      <%end%>
                    </table>
                  </div><!-- table-responsive -->
                </div><!-- col-md-6 -->
              </div>
            </div>
          </section>
          <div class="row">
      			<div class="col-md-8">
      				<section class="panel panel-default">
      					<div class="panel-body weather-row">
      							<img src="/weather_image.jpg" height="243" alt="">
      							<div class="weather-head">
      								weather forecast
      							</div>
      							<div class="form-group country-select">
      								<select class="width100p" data-placeholder="New York">
      									<option value="">New York</option>
      									<option value="">London</option>
      									<option value="">Australia</option>
      									<option value="">Canada</option>
      									<option value="">China</option>
      									<option value="">New York</option>
      								</select>
      							</div>
      						</div>

      				<div class="panel-footer">
      					<div class="row weather-full-info">
      						<div class="col-md-3 today-status">
      							<h1>Today</h1>
      							<span class="wi wi-day-cloudy"></span>
      							<div class="degree">37</div>
      						</div>
      						<div class="col-md-9">
      							<ul>
      								<li>
      									<h2>Tomorrow</h2>
      									<span class="wi wi-day-cloudy text-primary"></span>
      									<div class="statistics">32</div>
      								</li>
      								<li>
      									<h2>Mon</h2>
      									<span class="wi wi-day-cloudy text-danger"></span>
      									<div class="statistics">40</div>
      								</li>
      								<li>
      									<h2>Tue</h2>
      									<span class="wi wi-day-cloudy text-info"></span>
      									<div class="statistics">25</div>
      								</li>
      								<li>
      									<h2>Wed</h2>
      									<span class="wi wi-day-cloudy text-success"></span>
      									<div class="statistics">37</div>
      								</li>
      								<li>
      									<h2>Thu</h2>
      									<span class="wi wi-day-cloudy text-warning"></span>
      									<div class="statistics">15</div>
      								</li>
      								<li>
      									<h2>Fri</h2>
      									<span class="wi wi-day-cloudy"></span>
      									<div class="statistics">21</div>
      								</li>
      							</ul>
      						</div>
      					</div>
      				</div>
      			</section>
      		</div>

      		<div class="col-md-4">
      			<section class="panel panel-default">
      				<div class="clock-panel">
      					<h1>DECEMBER 16</h1>
      					<p class="text-left">2016, Friday</p>
      					<p class="text-left">7:53 PM</p>
      				</div>

      				<ul id="clock">
      					<li id="sec"></li>
      					<li id="hour"></li>
      					<li id="min"></li>
      				</ul>

      				<ul class="clock-category">
      					<li>
      						<a href="#" class="active">
      							<i class="fa fa-clock-o"></i>
      							<span>Clock</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Alarm</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Stop watch</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Timer</span>
      						</a>
      					</li>
      				</ul>
      			</section>
      		</div>
      	</div>

      </div><!-- contentpanel -->

      <%=render "shared/footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>

app/views/customers/new.html.erb
<%=render "signup/signup"%>

app/views/customers/show.html.erb
<%=render "shared/navbar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel">
          <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-md-8">
                  <div class="ibox float-e-margins">
                    <div class="ibox-title">
                      <h5>Order History</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>

                        <div class="ibox-content">
                            <table class="table table-hover no-margins">
                                <thead>
                                <tr>
                                  <%@fields.each do |f|%>
                                    <th><%=f%></th>
                                  <%end%>
                                </tr>
                                </thead>
                                <tbody>

                                <%@orders.each do |order|%>
                                  <tr>
                                      <%if order.state == "complete"%>
                                        <td><%=link_to order.id, order_path(order)%></td>
                                        <td><span  class="label label-primary"><%=order.state%></td>
                                        <td><%=order.checked_out_at%></td>
                                        <td><%=number_to_currency(order.total_price)%></td>
                                      <%else%>
                                      <%end%>
                                  </tr>
                                <%end%>
                                </tbody>
                                <tr>

                                </tr>
                            </table>
                        </div>

                    </div>
                </div>

                <div class="col-md-4">
                  <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Who Buy Your Product?</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>

                    <div class="ibox-content">
                        <ul class="todo-list m-t small-list">
                          <h5>Username</h5>
                          <li><%=@customer.username%></li>
                          <h5>E-mail</h5>
                          <li><%=@customer.email%></li>
                          <h5>Created At</h5>
                          <li><%=@customer.created_at%></li>
                        </ul>
                    </div>
                    </div>
                </div>
            </div>
        </div>
      </div><!-- contentpanel -->
    <%=render "shared/footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>