config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    # resources :sessions

    root "homes#index"
    scope :admin do
      root "dashboards#index"
      resources :categories
      resources :products
      resources :users
      resources :customers
      resources :orders
      get "invoice/:id" => "orders#invoice", :as => :invoice
    end
    scope :shopping do
      resources :homes
      get "customer_info/:id" => "customers#customer_info", :as => :customer_info
      get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
      patch "customer_info/:id" => "customers#update_customer_info"
      put "customer_info/:id" => "customers#update_customer_info"
      get "product_detail/:id" => "products#product_detail", :as => :product_detail
      resources :customers
    end



    mount ActionCable.server => '/cable'

    get "cart" => "cart#show"
    get "cart/add/:id" => "cart#add", :as => :add_to_cart
    post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
    post "cart/checkout" => "cart#checkout", :as => :checkout

    post 'session' => 'sessions#create', :as=> :session_customer
    get 'signup' => 'customers#new',:as=> :signup
    get 'logout' => 'sessions#destroy', :as => :logout
    get 'login' => 'sessions#new', :as => :login
    get "dashboard" => 'dashboards#index', :as => :dashboard_page

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :line_items

#Validation
  validates :product_name, presence: true
  validates :product_unit, presence: true
  validates :product_price, presence: true

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only: [:new,:edit,:update,:destroy]
  before_action :admin_only, only: [:new,:edit,:update,:destroy]

  def product_detail
    @product = Product.find(params[:id])
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @fields = ["ID","Product Name","Unit","Price","Category","Image","Name"]
    #   if session[:cart_id]
    #   @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_customer.orders.build
    # else
    #   if @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_customer
    #     @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_customer.orders.build
    #   end
    # end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    # @lines = LineItem.find(params[:id])
    # if session[:cart_id]
    #   @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_customer.orders.build
    # else
    #   if @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_customer
    #     @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_customer.orders.build
    #   end
    # end
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end
  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product =  current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def admin_only
      unless current_user.admin?
        redirect_to root_path, :alert => "Access denied."
      end
    end

    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name,:product_unit, :product_price, :image, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_category(product)
      if product.category.category_name == "Please Select Category"
        "Uncategory"
      else
        product.category.category_name
      end
    end

end

app/views/products/_form.html.erb
<%=render "shared/navbar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel">
          <section class="panel panel-default">
            <div class="panel-body weather-row">
              <div class="row">
                <div class="col-md-12">
                  <%=form_for product do |f|%>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="panel-btns">
                                <a href="#" class="panel-minimize tooltips" data-toggle="tooltip" title="Minimize Panel"><i class="fa fa-minus"></i></a>
                                <a href="#" class="panel-close tooltips" data-toggle="tooltip" title="Close Panel"><i class="fa fa-times"></i></a>
                            </div><!-- panel-btns -->
                            <h4 class="panel-title">Add Product</h4>
                            <p>This is an example of a form using a placeholder instead of label.</p>
                        </div><!-- panel-heading -->
                        <div class="panel-body">
                            <div class="row">

                                <div class="form-group col-md-6">
                                  <%=link_to "Add New Category", new_category_path, :class=>"btn btn-primary", :id=>"dis"%>
                                </div>

                                <div class="form-group col-md-12">
                                  <%=f.collection_select :category_id,Category.all,:id,:category_name%>
                                </div>


                                <div class="form-group col-md-4">
                                  <%=f.text_field :product_name, :class=>"form-control", :placeholder=>"Product Name"%>
                                </div>
                                <div class="form-group col-md-4">
                                  <%=f.number_field :product_unit, :class=>"form-control", :placeholder=>"Unit"%>
                                </div>
                                <div class="form-group col-md-4">
                                  <%=f.number_field :product_price, :class=>"form-control", :placeholder=>"Price"%>
                                </div>

                                  <div class="form-group col-md-4">
                                    <%=f.file_field :image,as: :file%>
                                  </div>

                            </div><!-- row -->
                        </div><!-- panel-body -->
                        <div class="panel-footer">
                          <%=f.submit "Add Product", :class=>"btn btn-primary"%>
                        </div><!-- panel-footer -->
                    </div><!-- panel -->
                  <%end%>
                </div><!-- col-md-6 -->
              </div><!-- row -->
            </div>
          </section>

          <div class="row">
      			<div class="col-md-8">
      				<section class="panel panel-default">
      					<div class="panel-body weather-row">
      							<img src="/weather_image.jpg" height="243" alt="">
      							<div class="weather-head">
      								weather forecast
      							</div>
      							<div class="form-group country-select">
      								<select class="width100p" data-placeholder="New York">
      									<option value="">New York</option>
      									<option value="">London</option>
      									<option value="">Australia</option>
      									<option value="">Canada</option>
      									<option value="">China</option>
      									<option value="">New York</option>
      								</select>
      							</div>
      						</div>

      				<div class="panel-footer">
      					<div class="row weather-full-info">
      						<div class="col-md-3 today-status">
      							<h1>Today</h1>
      							<span class="wi wi-day-cloudy"></span>
      							<div class="degree">37</div>
      						</div>
      						<div class="col-md-9">
      							<ul>
      								<li>
      									<h2>Tomorrow</h2>
      									<span class="wi wi-day-cloudy text-primary"></span>
      									<div class="statistics">32</div>
      								</li>
      								<li>
      									<h2>Mon</h2>
      									<span class="wi wi-day-cloudy text-danger"></span>
      									<div class="statistics">40</div>
      								</li>
      								<li>
      									<h2>Tue</h2>
      									<span class="wi wi-day-cloudy text-info"></span>
      									<div class="statistics">25</div>
      								</li>
      								<li>
      									<h2>Wed</h2>
      									<span class="wi wi-day-cloudy text-success"></span>
      									<div class="statistics">37</div>
      								</li>
      								<li>
      									<h2>Thu</h2>
      									<span class="wi wi-day-cloudy text-warning"></span>
      									<div class="statistics">15</div>
      								</li>
      								<li>
      									<h2>Fri</h2>
      									<span class="wi wi-day-cloudy"></span>
      									<div class="statistics">21</div>
      								</li>
      							</ul>
      						</div>
      					</div>
      				</div>
      			</section>
      		</div>

      		<div class="col-md-4">
      			<section class="panel panel-default">
      				<div class="clock-panel">
      					<h1>DECEMBER 16</h1>
      					<p class="text-left">2016, Friday</p>
      					<p class="text-left">7:53 PM</p>
      				</div>

      				<ul id="clock">
      					<li id="sec"></li>
      					<li id="hour"></li>
      					<li id="min"></li>
      				</ul>

      				<ul class="clock-category">
      					<li>
      						<a href="#" class="active">
      							<i class="fa fa-clock-o"></i>
      							<span>Clock</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Alarm</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Stop watch</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Timer</span>
      						</a>
      					</li>
      				</ul>
      			</section>
      		</div>
      	</div>

      </div><!-- contentpanel -->

      <%=render "shared/footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<%=render "shared/navbar"%>

	<section>
			<div class="mainwrapper">
				<%=render "shared/left-panel"%>

					<div class="mainpanel">
							<div class="contentpanel contentpanel-wizard">
                <div class="row" style="background:#fff;padding:10px;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;margin-bottom:15px;">
                  <div class="col-md-12">
                    <h5 class="lg-title mb5">Table With Actions</h5>
                    <p class="mb20">An example of table with actions in every rows.</p>
                    <div class="table-responsive">
	                    <table class="table mb30">
	                      <thead>
	                        <tr>
														<%@fields.each do |f|%>
															<th><%=f%></th>
														<%end%>
	                        </tr>
	                      </thead>

                        <%@products.each do |product|%>
                        <tbody>
                          <tr>
                            <td><%=product.id%></td>
                            <td><%=product.product_name %></td>
                            <td><%=product.product_unit%></td>
                            <td><%=product.product_price%></td>
                            <td><%=product_category(product)%></td>
                            <td style="width: 15%;"><%=image_tag(product.image,:class=>"image-table-data",:style=>"width:100%;")%></td>
                            <td><%=product.user.username%></td>
	                          <td class="table-action text-right">
															<%if current_user.try(:admin?)%>
																<%=link_to product, :class => 'btn btn-success btn-simple btn-xs',:rel=>"tooltip",:title=>"View" do %>
																	<i class="fa fa-eye" style="font-size: 15px;color:white"></i>
																<%end%>
																<%=link_to edit_product_path(product), :class => 'btn btn-success btn-simple btn-xs',:rel=>"tooltip",:title=>"Edit" do %>
																<i class="fa fa-pencil" style="font-size: 15px;color:white"></i>
																<%end%>
																<%=link_to product,method: :delete,data: {confirm: "Are You Sure?"},:title=>"Delete", :class => 'btn btn-danger btn-simple btn-xs',:rel=>"tooltip",:title=>"Delete" do %>
																<i class="fa fa-trash-o" style="font-size: 15px;color:white"></i>
																<%end%>

																<%else%>
																<%=link_to product,:title=>"View",:class=>"tooltips" do %>
																<i class="fa fa-eye"></i>
																<%end%>

															<%end%>

	                          </td>
	                        </tr>
	                      </tbody>
												<%end%>
	                    </table>
                    </div><!-- table-responsive -->
                  </div><!-- col-md-6 -->
                </div>

                <div class="row">

                  <div class="col-md-8">
                    <section class="panel panel-default">
                      <div class="panel-body weather-row">
                        <img src="/weather_image.jpg" height="243" alt="">
                        <div class="weather-head">
                          weather forecast
                        </div>
                        <div class="form-group country-select">
                          <select class="width100p" data-placeholder="New York">
                            <option value="">New York</option>
                            <option value="">London</option>
                            <option value="">Australia</option>
                            <option value="">Canada</option>
                            <option value="">China</option>
                            <option value="">New York</option>
                          </select>
                        </div>
                      </div>

                  <div class="panel-footer">
                    <div class="row weather-full-info">
                      <div class="col-md-3 today-status">
                        <h1>Today</h1>
                        <span class="wi wi-day-cloudy"></span>
                        <div class="degree">37</div>
                      </div>
                      <div class="col-md-9">
                        <ul>
                          <li>
                            <h2>Tomorrow</h2>
                            <span class="wi wi-day-cloudy text-primary"></span>
                            <div class="statistics">32</div>
                          </li>
                          <li>
                            <h2>Mon</h2>
                            <span class="wi wi-day-cloudy text-danger"></span>
                            <div class="statistics">40</div>
                          </li>
                          <li>
                            <h2>Tue</h2>
                            <span class="wi wi-day-cloudy text-info"></span>
                            <div class="statistics">25</div>
                          </li>
                          <li>
                            <h2>Wed</h2>
                            <span class="wi wi-day-cloudy text-success"></span>
                            <div class="statistics">37</div>
                          </li>
                          <li>
                            <h2>Thu</h2>
                            <span class="wi wi-day-cloudy text-warning"></span>
                            <div class="statistics">15</div>
                          </li>
                          <li>
                            <h2>Fri</h2>
                            <span class="wi wi-day-cloudy"></span>
                            <div class="statistics">21</div>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </section>
              </div>

              <div class="col-md-4">
                <section class="panel panel-default">
                  <div class="clock-panel">
										<p><%=DateTime.now%></p>
                  </div>

                  <ul id="clock">
                    <li id="sec"></li>
                    <li id="hour"></li>
                    <li id="min"></li>
                  </ul>

                  <ul class="clock-category">
                    <li>
                      <a href="#" class="active">
                        <i class="fa fa-clock-o"></i>
                        <span>Clock</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="fa fa-clock-o"></i>
                        <span>Alarm</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="fa fa-clock-o"></i>
                        <span>Stop watch</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="fa fa-clock-o"></i>
                        <span>Timer</span>
                      </a>
                    </li>
                  </ul>
                </section>
              </div>
            </div>
					</div><!-- contentpanel -->
					<%=render "shared/footer"%>
				</div><!-- mainpanel -->
		</div><!-- mainwrapper -->
	</section>

app/views/products/new.html.erb
<%= render 'form', product: @product %>

app/views/products/product_detail.html.erb
<%=render "shared/end-user-nav-bar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/end-user-left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel">
          <section class="panel panel-default">
            <div class="weather-row">
            <div class="wrapper wrapper-content animated fadeInRight">
              <div class="row">
                  <div class="col-lg-12">
                      <div class="ibox product-detail">
                              <div class="row">
                                  <div class="col-md-5">
                                      <div class="product-images">
                                        <%if @product.image.blank?%>
                                          <div>
                                            <div class="image-imitation">
                                              Image Not Found
                                            </div>
                                          </div>
                                          <div>
                                            <div class="image-imitation">
                                              Image Not Found
                                            </div>
                                          </div>
                                          <%else%>
                                          <div>
                                            <div class="image-imitation">
                                              <%=image_tag(@product.image, :class=>"image-detail")%>
                                            </div>
                                          </div>
                                        <%end%>

                                      </div>
                                  </div>
                                  <div class="col-md-7">

                                      <h2 class="font-bold m-b-xs">
                                        <%=@product.product_name%>
                                      </h2>
                                      <small class="text-muted">Category (<%=@product.category.category_name%>)</small>
                                      <p>Many desktop publishing packages and web page editors now.</p>
                                      <div class="m-t-md">
                                          <h2 class="product-main-price">$<%=@product.product_price%> <small class="text-muted">Category (<%=@product.category.category_name%>)</small> </h2>
                                      </div>
                                      <hr>

                                      <h4>Product description</h4>

                                      <div class="small text-muted">
                                        <%if @product.category.description.blank?%>
                                          <p>No Description</p>
                                          <%else%>
                                          <%=@product.category.description%>
                                        <%end%>

                                      </div>

                                      <hr>

                                      <h4>Product Stock</h4>

                                      <div class="small text-muted">
                                        <%=@product.product_unit%>
                                      </div>

                                      <hr>

                                      <div>
                                          <div class="btn-group">

                                              <%= link_to add_to_cart_path, :class => 'btn btn-primary btn-sm',:rel=>"tooltip",:title=>"Edit",:style=>"margin-right:10px;" do %>
                                                <i class="fa fa-pencil" style="font-size: 15px;"></i> Add To Cart
                                              <% end %>

                                              <%= link_to root_path, :class => 'btn btn-danger btn-sm',:rel=>"tooltip",:title=>"Cancle" do %>
                                                <i class="fa fa-trash-o" style="font-size: 15px;"></i> Cancle
                                              <% end %>

                                          </div>
                                      </div>

                                  </div>
                              </div>


                          <div class="ibox-footer">
                              <span class="pull-right">
                                  Created At- <i class="fa fa-clock-o"></i> <%=@product.created_at%>
                              </span>
                              The description
                          </div>
                      </div>

                  </div>
              </div>
            </div>
            </div>
          </section>
          <div class="row">
      			<div class="col-md-8">
      				<section class="panel panel-default">
      					<div class="panel-body weather-row">
      							<img src="/weather_image.jpg" height="243" alt="">
      							<div class="weather-head">
      								weather forecast
      							</div>
      							<div class="form-group country-select">
      								<select class="width100p" data-placeholder="New York">
      									<option value="">New York</option>
      									<option value="">London</option>
      									<option value="">Australia</option>
      									<option value="">Canada</option>
      									<option value="">China</option>
      									<option value="">New York</option>
      								</select>
      							</div>
      						</div>

      				<div class="panel-footer">
      					<div class="row weather-full-info">
      						<div class="col-md-3 today-status">
      							<h1>Today</h1>
      							<span class="wi wi-day-cloudy"></span>
      							<div class="degree">37</div>
      						</div>
      						<div class="col-md-9">
      							<ul>
      								<li>
      									<h2>Tomorrow</h2>
      									<span class="wi wi-day-cloudy text-primary"></span>
      									<div class="statistics">32</div>
      								</li>
      								<li>
      									<h2>Mon</h2>
      									<span class="wi wi-day-cloudy text-danger"></span>
      									<div class="statistics">40</div>
      								</li>
      								<li>
      									<h2>Tue</h2>
      									<span class="wi wi-day-cloudy text-info"></span>
      									<div class="statistics">25</div>
      								</li>
      								<li>
      									<h2>Wed</h2>
      									<span class="wi wi-day-cloudy text-success"></span>
      									<div class="statistics">37</div>
      								</li>
      								<li>
      									<h2>Thu</h2>
      									<span class="wi wi-day-cloudy text-warning"></span>
      									<div class="statistics">15</div>
      								</li>
      								<li>
      									<h2>Fri</h2>
      									<span class="wi wi-day-cloudy"></span>
      									<div class="statistics">21</div>
      								</li>
      							</ul>
      						</div>
      					</div>
      				</div>
      			</section>
      		</div>

      		<div class="col-md-4">
      			<section class="panel panel-default">
      				<div class="clock-panel">
      					<h1>DECEMBER 16</h1>
      					<p class="text-left">2016, Friday</p>
      					<p class="text-left">7:53 PM</p>
      				</div>

      				<ul id="clock">
      					<li id="sec"></li>
      					<li id="hour"></li>
      					<li id="min"></li>
      				</ul>

      				<ul class="clock-category">
      					<li>
      						<a href="#" class="active">
      							<i class="fa fa-clock-o"></i>
      							<span>Clock</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Alarm</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Stop watch</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Timer</span>
      						</a>
      					</li>
      				</ul>
      			</section>
      		</div>
      	</div>

      </div><!-- contentpanel -->

      <%=render "shared/end-user-footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>